import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sfPro = localFont({
  src: [
    {
      path: "./fonts/SFPRODISPLAYBOLD.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/SFPRODISPLAYMEDIUM.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/SFPRODISPLAYREGULAR.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SFPRODISPLAYSEMIBOLDITALIC.woff2",
      weight: "600",
      style: "italic",
    },
  ],
  variable: "--font-sf-pro",
});
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${sfPro.className} h-full antialiased`}
    >
      <body className=" min-h-full flex flex-col">{children}</body>
    </html>
  );
}
